---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flux-helm-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-helm-operator
    spec:
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: flux-helm-operator
        # There are no ":latest" images for helm-operator. Find the most recent
        # release or image version at https://quay.io/weaveworks/helm-operator
        # and replace the tag here.
        image: quay.io/weaveworks/helm-operator:alpha
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        # replace (at least) the following URL
        - --git-url=git@github.com:weaveworks/flux-helm-test
        - --git-branch=master
        - --git-charts-path=charts
